title: PC Engines Documentation
description: A collection of manuals and instructions
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
markdown: kramdown
highlighter: rouge

# remote_theme: pages-themes/tactile@v0.2.0
#  plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one